### ISSUE TITLE
Decide features for Starbucks application

### ISSUE THREAD

**Issue by pooja27** [shubhamvadhera/cmpe281-teamproject#3]

**Comment by shubhamvadhera** [comment]
Login page to be the first page - user cannot view products without logging in

**Comment by shubhamvadhera** [comment]
Must have features - login page, product catalogue, user sign up

**Comment by shubhamvadhera** [comment]
To store user data, address or only email is sufficient ?

**Comment by shubhamvadhera** [comment]
Additional - UI improvement
